AWSTemplateFormatVersion: "2010-09-09"
Description: 2 cloudfronts each with an s3 bucket

Resources:
  WebsiteBucket1:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl

  WebsiteBucketPolicy1:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket1
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: "*"
          Action:
          - "s3:GetObject"
          Resource: !Sub arn:aws:s3:::${WebsiteBucket1}/*

  WebsiteBucket2:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl

  WebsiteBucketPolicy2:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket2
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: "*"
          Action:
          - "s3:GetObject"
          Resource: !Sub arn:aws:s3:::${WebsiteBucket2}/*

  CloudFrontDistribution1:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: true
          TargetOriginId: webpage
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index1.html
        Enabled: true
        Origins:
        - DomainName: !GetAtt WebsiteBucket1.DomainName
          Id: webpage
          S3OriginConfig:
            OriginAccessIdentity:
              Ref: AWS::NoValue
        PriceClass: PriceClass_100

  CloudFrontDistribution2:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: true
          TargetOriginId: webpage
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index2.html
        Enabled: true
        Origins:
        - DomainName: !GetAtt WebsiteBucket2.DomainName
          Id: webpage
          S3OriginConfig:
            OriginAccessIdentity:
              Ref: AWS::NoValue
        PriceClass: PriceClass_100

Outputs:
  WebsiteBucket1:
    Value: !Ref WebsiteBucket1