AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket cleanup function
Resources:
  LambdaS3Role:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      Policies:
      - PolicyDocument:
          Statement:
          - Action: s3:*
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: root
    Type: AWS::IAM::Role
  S3CleanupLambda:
    Properties:
      CodeUri: s3://binx-cleanup-lambda/1ecd1301f8a3b1a44ba59351e0e32de7
      Environment:
        Variables:
          REGION: eu-west-1
      Events:
        DailySchedule:
          Properties:
            Schedule: rate(1 day)
          Type: Schedule
      Handler: s3_cleanup.handler
      Role:
        Fn::GetAtt:
        - LambdaS3Role
        - Arn
      Runtime: python3.6
      Timeout: 30
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
